apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: tarunjangra/mcs-notification-service:latest
          env:
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  key: smtp_username
                  name: smtp-secrets
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: smtp_password
                  name: smtp-secrets
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              valueFrom:
                configMapKeyRef:
                  key: SPRING_KAFKA_BOOTSTRAP-SERVERS
                  name: common-config
            - name: SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL
                  name: notification-service-config
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  key: LOKI_URL
                  name: common-config
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
                  name: common-config
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: v1
data:
  smtp_password: OTFiNzVmZTkwYTBhZDY=
  smtp_username: MGJhZmFkMmIxYjE1NWI=
kind: Secret
metadata:
  name: smtp-secrets
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL: "http://schema-registry.default.svc.cluster.local:8081"